tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/versions"
tap "caskroom/cask"
brew "cocoapods"
brew "carthage"
brew "cloc"
brew "gnuplot", args: ["with-aquaterm"]
brew "graphviz"
brew "openssl"
brew "mongodb"
brew "mysql"
brew "node"
brew "plantuml"
brew "pyenv"
brew "wget"
